version: '3'

services:
  nano-beta-node:
    image: nanocurrency/nano-beta:latest
    container_name: nano-beta-node
    hostname: nano-beta-node
    environment:
      - TERM=xterm
    restart: unless-stopped
    ports:
      - "54000:54000/udp"
      - "54000:54000"
      - "::1:55000:55000"
    volumes:
      - ./nano-beta-node:/root

  nano-node-monitor:
    image: nanotools/nanonodemonitor
    container_name: nano-node-monitor
    hostname: nano-node-monitor
    restart: unless-stopped
    volumes:
      - ./nano-node-monitor:/opt/nanoNodeMonitor
    ports:
      - "80:80"
      
  watchtower:
    image: v2tec/watchtower
    container_name: watchtower
    restart: unless-stopped
    command: watchtower nano-beta-node nano-node-monitor
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    external:
      name: nano-beta-node-network
